config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :portfolios
  get :portfolio, to: 'pages#portfolio'
  get :about, to: 'pages#about'
  get :references, to: 'pages#references'
  get :contact, to: 'pages#contact'
  get :dev, to: 'pages#dev'
  get :cv, to: 'pages#cv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def about
  end

  def references
  end

  def contact
  end

  def dev
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= meta_title %></title>
     <%= action_cable_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon"> %>
    <%= favicon_link_tag %>


    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css?family=Limelight" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<% content_for :meta_title, "About - Owen Baldwin" %>


<div class="portfolio-background">
  <div class="portfolio-body">
    <div class="portfolio-body-inner">
      <div class="diamond-deco-container container">
        <div class="diamond-deco-content">

          <div class="portfolio-titles">
            <main class="main">
              <div class="button">
                <div class="button__ornament button__ornament--vertical">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>

                <div class="button__ornament button__ornament--horisontal">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>
                <span class="button__label">ABOUT</span>
              </div>
            </main>
          </div>

          <div class="about-box">
            <%# <div class="image-box"> %>
              <%= image_tag "about-1-shadow.jpeg", class: "about-image" %>
              <div class="inset-shadow"></div>
            <%# </div> %>
            <div class="about-text">
              <p>Owen Baldwin is an English film and media composer, songwriter and musician.</p>
              <p>He has studied classical music in high school and then went on to study songwriting and music performance at the British and Irish Modern Music institute (BIMM) in London.
              He was awarded with a Bachelor in Arts and two BTEC Diplomas.</p>
              <p>Orchestral composers such as Gustav Holst, Ralph Vaughan Williams, John Williams and Danny Elfman are among his biggest source of inspiration, as well as
              bands such as the Doors, Pink Floyd and the Moody Blues</p>

            </div>
          </div>

          <div class="triple-diamond-deco-container container">
            <div class="left-line"></div>
            <div class="right-line"></div>
            <div class="small-diamond-left"></div>
            <div class="small-diamond-right"></div>
            <div class="large-diamond"></div>
          </div>

          <div class="about-box">
            <div class="about-text">
              <p>Owen has experience writing in genres such as orchestral, rock, folk, electronic music and more, and for a wide variety of instruments.</p>
              <p>His music is now available on all streaming platforms, Bandcamp and YouTube.</p>
              <p>More music will be released in the coming months, alternating between soundtracks and compositions. Stay tuned!</p>
            </div>
            <%= image_tag "about-2-shadow.jpeg", class: "about-image" %>
          </div>

        </div>
        <div class="diamond-deco-square-left-top"></div>
        <div class="diamond-deco-square-left-bottom"></div>
        <div class="diamond-deco-square-right-top"></div>
        <div class="diamond-deco-square-right-bottom"></div>
        <div class="diamond-deco-tall-outer"></div>
        <div class="diamond-deco-tall-inner"></div>
        <div class="diamond-deco-wide-outer"></div>
        <div class="diamond-deco-wide-inner"></div>
      </div>

    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :meta_title, "Contact - Owen Baldwin" %>


<div class="contact-background">
  <div class="contact-body">

  <div class="triple-deco-container container contact-container">
    <div class="triple-deco-content">
      <%# <div data-tf-widget="GObbOyoP" data-tf-iframe-props="title=Get in touch template (copy)" style="width:100%;height:400px;"></div>
      <script src="//embed.typeform.com/next/embed.js"></script> %>

      <div data-tf-widget="GObbOyoP" data-tf-iframe-props="title=Get in touch template (copy)" data-tf-medium="snippet" style="width:100%;height:400px;"></div>
      <script src="//embed.typeform.com/next/embed.js"></script>
    </div>
    <div class="triple-deco-tall"></div>
    <div class="triple-deco-mid"></div>
    <div class="triple-deco-wide"></div>
  </div>

  </div>
</div>

app/views/pages/dev.html.erb
<% content_for :meta_title, "Web Development - Owen Baldwin" %>


<div class="portfolio-background">


  <div class="portfolio-body">
    <div class="portfolio-body-inner">
      <div class="square-deco-container container">
        <div class="square-deco-content">
          <div class="dev-title">
            <h1>WEB DEVELOPMENT</h1>
            <p>I also work as a full stack web developer. Here you will find my portfolio as well as links to my Github and projects!</p>

            <main class="main">
              <div class="button">
                <div class="button__ornament button__ornament--vertical">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>

                <div class="button__ornament button__ornament--horisontal">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>
                <span class="button__label"><%= link_to "Github page", "https://github.com/owenbaldwin", :target => "_blank", id: "dev-buttons" %></span>
              </div>
            </main>



          </div>


          <div class="dev-projects">
            <div class="dev-item">
              <h2>FILMPOD</h2>
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <%= image_tag "filmpod1.png", class: "d-block w-100", alt: "First slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod2.png", class: "d-block w-100", alt: "Second slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod3.png", class: "d-block w-100", alt: "Third slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod4.png", class: "d-block w-100", alt: "Fourth slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod5.png", class: "d-block w-100", alt: "Fifth slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod6.png", class: "d-block w-100", alt: "Sixth slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "filmpod7.png", class: "d-block w-100", alt: "Seventh slide" %>
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
              <div class="item-description">
                <p>Filmpod is a project management web app for film productions. It allows direction members and head of departments to send out tasks to their team mates, who in turn send back submissions.
                If approved by a superior, these submissions (photos of costumes, of locations, of actors, snippets of audio etc...) are pinned to a moodboard.
                Each department has a moodboard, accessible by all crew members. This allows the whole team to know where the film is at and what the aesthetics are. No more trouble conveying the vision for the film, everyone is on the same page!
                And thanks to the task and submission management system, no more drowning in a sea of emails!
                <br>This app is still in development with fellow Le Wagon graduates Zoe Bell, Emma Zurstrassen and Joe Waymark.</p>



                <main class="main">
                  <div class="button">
                    <div class="button__ornament button__ornament--vertical">
                      <div class="button__ornament-top-bottom"></div>
                      <div class="button__ornament-left-right"></div>
                    </div>

                    <div class="button__ornament button__ornament--horisontal">
                      <div class="button__ornament-top-bottom"></div>
                      <div class="button__ornament-left-right"></div>
                    </div>
                    <span class="button__label"><%= link_to "Visit Filmpod", "http://www.filmpod.net/", :target => "_blank", id: "dev-buttons" %></span>
                  </div>
                </main>


              </div>
            </div>


            <div class="dev-item">
              <h2>ISLEBNB</h2>
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <%= image_tag "islebnb1.png", class: "d-block w-100", alt: "First slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "islebnb2.png", class: "d-block w-100", alt: "Second slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "islebnb3.png", class: "d-block w-100", alt: "Third slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "islebnb4.png", class: "d-block w-100", alt: "Fourth slide" %>
                  </div>
                  <div class="carousel-item">
                    <%= image_tag "islebnb5.png", class: "d-block w-100", alt: "Fifth slide" %>
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
              <div class="item-description">
                <p>IsleBnB is a clone of AirBnB. It was built with fellow Le Wagon graduates Zoe Bell, Emma Zurstrassen and Joe Waymark.</p>


                <main class="main">
                  <div class="button">
                    <div class="button__ornament button__ornament--vertical">
                      <div class="button__ornament-top-bottom"></div>
                      <div class="button__ornament-left-right"></div>
                    </div>

                    <div class="button__ornament button__ornament--horisontal">
                      <div class="button__ornament-top-bottom"></div>
                      <div class="button__ornament-left-right"></div>
                    </div>
                    <span class="button__label"><%= link_to "Visit IsleBnB", "https://airbnb-owenbaldwin.herokuapp.com/", :target => "_blank", id: "dev-buttons" %></span>
                  </div>
                </main>
              </div>
            </div>
          </div>



        </div>
        <div class="square-deco-inner"></div>
        <div class="square-deco-square-left-top"></div>
        <div class="square-deco-square-left-bottom"></div>
        <div class="square-deco-square-right-top"></div>
        <div class="square-deco-square-right-bottom"></div>
        <div class="square-deco-tall"></div>
        <div class="square-deco-wide"></div>
      </div>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :meta_title, "Home - Owen Baldwin" %>


<div class="portfolio-background">


  <div class="portfolio-body">
    <div class="portfolio-body-inner">
      <div class="square-deco-container container">
        <div class="square-deco-content">
          <div class="home-banner">
            <%= image_tag "homepic.jpeg", class: "home-image" %>
          </div>
          <div class="home-subs"> 
            <h1>FILM COMPOSER</h1>
            <h1>SONGWRITER</h1>
            <h1>MUSICIAN</h1>
          </div>

          <div class="home-text">
            <p>I am a freelance composer, arranger and songwriter.  I write scores for films and all sort of visual projects. I also write arrangements for other people's songs in a wide variety of genres.</p>
            <p>Check out my portfolio to listen to previous releases as well as excerpts of soundtracks I have composed.
            You can find my sound design showreel at the bottom of the 'Portfolio' page.</p>
            <p>You can also contact me if you need music for your visual projects or if you need a full arrangement for your songs.</p>
          </div>






        </div>
        <div class="square-deco-inner"></div>
        <div class="square-deco-square-left-top"></div>
        <div class="square-deco-square-left-bottom"></div>
        <div class="square-deco-square-right-top"></div>
        <div class="square-deco-square-right-bottom"></div>
        <div class="square-deco-tall"></div>
        <div class="square-deco-wide"></div>
      </div>

    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<% content_for :meta_title, "Portfolio - Owen Baldwin" %>


<div class="portfolio-background">
  <div class="portfolio-banner">
    <%= image_tag "portfoliobg.png", class: "portfolio-banner-image" %>
    <div class="inset-shadow"></div>
  </div>


  <div class="portfolio-body">
    <div class="portfolio-body-inner">

      <div class="triple-deco-container container">
        <div class="triple-deco-content">

          <div class="portfolio-titles">
            <main class="main">
              <div class="button">
                <div class="button__ornament button__ornament--vertical">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>

                <div class="button__ornament button__ornament--horisontal">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>
                <span class="button__label">COMPOSITIONS</span>
              </div>
            </main>
          </div>


          <div class="youtube-video">
            <iframe  class="yt-video-item" src="https://www.youtube.com/embed/571oJHujkKg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>      <%# <video src="https://youtu.be/571oJHujkKg" width="740" height="480">Video not supported</video> %>
          </div>
          <div class="spotify">
            <iframe src="https://open.spotify.com/embed/track/07sqlvxtD0iJO7Hwz2ovqH?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" class="spotify-players"></iframe>
            <iframe src="https://open.spotify.com/embed/track/10FhAOdTdBuHo6qgCFHlvj?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" class="spotify-players"></iframe>
            <iframe src="https://open.spotify.com/embed/track/5U2mPu3VGJYdaWYyK1aPga?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" class="spotify-players"></iframe>
          </div>
          <div class="spotify-item">
            <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/941866165&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/owen-baldwin-3" title="Owen A. Baldwin" target="_blank" style="color: #cccccc; text-decoration: none;">Owen A. Baldwin</a> · <a href="https://soundcloud.com/owen-baldwin-3/sets/portfolio" title="Portfolio" target="_blank" style="color: #cccccc; text-decoration: none;">Portfolio</a></div>
          </div>

          <div class="title-deco-container container">
            <div class="content content-default"></div>
            <div class="content-dot"></div>
            <div class="main-diamond-outer"></div>
            <div class="main-diamond-inner"></div>
            <div class="mid-diamond-left"></div>
            <div class="mid-diamond-right"></div>
            <div class="small-diamond-left-top"></div>
            <div class="small-diamond-left-bottom"></div>
            <div class="small-diamond-right-top"></div>
            <div class="small-diamond-right-bottom"></div>
          </div>

          <div class="portfolio-titles">
            <main class="main">
              <div class="button">
                <div class="button__ornament button__ornament--vertical">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>

                <div class="button__ornament button__ornament--horisontal">
                  <div class="button__ornament-top-bottom"></div>
                  <div class="button__ornament-left-right"></div>
                </div>
                <span class="button__label">SOUNDTRACKS AND FILMS</span>
              </div>
            </main>

            <div>
              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/CthKzYky6Aw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>'All The Wives In Attics' (Coming Soon) Teaser (Dir. Dagmar Scheibenreif, Prod. Euras Films), music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/kO4mgv8yYXI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>'Burning Letters' (2021) Trailer (Dir. J.H. Greene), music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/42P76Ov9Kwg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>'Burning Letters' (2021)  Full Film (Dir. J.H. Greene), music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/msIseygR45k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Submission for the Marvin Hamlisch International Music Awards, music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/mPNDJZH0S8M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>'From The Corner Of My Eye Teaser' 2 - Feature film currently in pre-production, stay tuned!</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/t9mbB8d_g90" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Submission for the Indie Film Music Contest​, music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/Kk5oBAeovJQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Score submission for the composers choice contest, music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/4Bi92_fJiZQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Standing On Your Grave (Dir. Adam Howe, 2020), music by Owen A. Baldwin and Paul Drilhon</p>
              </div>

              <div class="spotify-item">
                <iframe src="https://open.spotify.com/embed/album/4QfRqsC0Q2S0v8GNivAjnJ?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
                <p>Standing On Your Grave Original Soundtrack (Dir. Adam Howe, 2020), music by Owen A. Baldwin and Paul Drilhon</p>
              </div>

              <div class="spotify-item">
                <iframe src="https://open.spotify.com/embed/album/5SzFfy5S2RwoYo6Poymly9?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
                <p>Marvellous Day Original Soundtrack (Dir. Lawra Eb, 2018), music by Owen A. Baldwin</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/lTw-9XLT4C4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Robbie Lester's Acting Showreel, Music and Sound Design by Owen A. Baldwin and Paul Drilhon</p>
              </div>

              <div class="youtube-video">
                <iframe  class="yt-video-item" src="https://www.youtube.com/embed/DfCTNp7LMJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <p>Video Game Open Sequence Soundtrack, music by Owen A. Baldwin</p>
              </div>
            </div>
          </div>


        </div>
        <div class="triple-deco-tall"></div>
        <div class="triple-deco-mid"></div>
        <div class="triple-deco-wide"></div>
      </div>

    </div>
  </div>
</div>

app/views/portfolios/index.html.erb
<%# <div class="portfolio-background">
  <div class="portfolio-banner">
    <h1>PORTFOLIO</h1>
    <div class="subtitles">
      <h3>COMPOSITIONS</h3>
      <h3>SOUNDTRACKS</h3>
    </div>
    <h6>Scroll down</h6>
  </div>

  <div class="portfolio-body">
    <%# <div> %>
      <%= video_tag "https://youtu.be/571oJHujkKg", class: "video-tag"%>
      <%# <video src="https://youtu.be/571oJHujkKg" width="740" height="480">Video not supported</video> %>
    <%# </div> %>
  </div>
</div> %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div>
    <ul class="socialm">
      <li>
        <a href="https://open.spotify.com/artist/3Omvo528Fr42vzJibzsfyt?si=tTDnJ1-MQpe7j_KgszekkA" target="_blank">
          <i class="fab fa-spotify"></i></a></li>
      <li>
        <a href="https://www.instagram.com/owen_a_baldwin/?hl=en" target="_blank">
          <i class="fab fa-instagram"></i></a></li>
      <li>
        <a href="https://www.facebook.com/owenabaldwinmusic/" target="_blank">
          <i class="fab fa-facebook-square"></i></a></li>
      <li>
        <a href="https://www.youtube.com/channel/UCd9Tb2M_DRf-J5SXkhxCb1w" target="_blank">
          <i class="fab fa-youtube"></i></a></li>
      <li>
        <a href="https://www.linkedin.com/in/owenajbaldwin/" target="_blank">
          <i class="fab fa-linkedin"></i></li>
    </ul>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-outer">

  <div class="navbar-inner">
    <div class="name-title">
      <h2>OWEN BALDWIN</h2>
    </div>

    <div class="navbar">
      <input type="checkbox" class="menu-btn" id="menu-btn" />
      <label for="menu-btn" class="menu-icon"><span class="nav-icon"></span></label>

      <ul class="tabs">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "PORTFOLIO", portfolio_path %></li>
        <li><%= link_to "ABOUT", about_path %></li>
        <li><%= link_to "REFERENCES", references_path %></li>
        <li><%= link_to "CONTACT", contact_path %></li>
        <li><%= link_to "WEB DEVELOPMENT", dev_path %></li>
      </ul>
    </div>
  </div>
</div>